name: Manual NRK Web Scrape

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set file permissions
      run: |
        chmod -R 755 scripts/nrk/inland
        chmod -R 755 scripts/nrk/global
    - name: Run scripts
      run: |
        python scripts/nrk/inland/nrk_inland.py
        python scripts/nrk/global/nrk_global.py
