name: Manual NRK Web Scrape

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set file permissions
        run: |
          chmod -R 755 scripts/nrk/inland/
          chmod -R 755 scripts/nrk/global/
          chmod -R +w scripts/nrk/inland/
          chmod -R +w scripts/nrk/global/
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/nrk/inland/requirements.txt
          pip install -r scripts/nrk/global/requirements.txt
      - name: Run scripts
        run: |
          sudo python 3 scripts/nrk/inland/nrk_inland.py
          sudo python 3 scripts/nrk/global/nrk_global.py
